name: PR Diff Check

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  check-diff:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Save PR version of state.csv
        run: mv state.csv state-pr.csv

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      # Wait for all 'status' checks to complete
      - name: Wait for CI
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: CI # Replace with your CI job names
          ref: ${{ github.event.pull_request.head.sha }}

      # Ensure all checks are successful
      - name: Verify CI success
        run: |
          if [ "${{ steps.wait-for-ci.outputs.conclusion }}" != "success" ]; then
            echo "CI checks failed"
            exit 1
          fi

      # Compare state.csv in PR and main branch, and post comment
      - name: Compare state.csv and Post Comment
        run: |
          # Diff between state.csv in main and in PR
          DIFF=$(diff -u state.csv state-pr.csv) || true

          # Posting the diff as a comment
          echo "$DIFF" | gh pr comment ${{ github.event.pull_request.number }} --body "Diff between \`state.csv\` in main and PR:\n\`\`\`\n$DIFF\n\`\`\`"
